import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import {
  FrameDocument,
  FrameTerminalDocument,
  isFullHtmlDocument,
} from '../../src/ui/pages/frame-document.js';

/**
 * Half the product's stated value is "every artifact is an HTML page", and that half shipped as a
 * raw fragment: `/a/:id/frame` returned `content.content` verbatim, with no doctype, no charset,
 * no viewport and no stylesheet, so agent HTML rendered in Times New Roman against the UA's 8px
 * body margin — at a public, directly-navigable URL.
 *
 * The shell wraps; it never rewrites. These tests hold that line, because the frame is also the
 * product's security boundary.
 */
const appCss = readFileSync('src/ui/assets/app.css', 'utf8').toLowerCase();

describe('full-document detection', () => {
  it('recognises content that already declares its own document', () => {
    for (const content of [
      '<!doctype html><h1>Hi</h1>',
      '<!DOCTYPE HTML><html><body>Hi</body></html>',
      '  \n<!doctype html>\n<html lang="en"></html>',
      '<html><head></head><body>Hi</body></html>',
      '﻿<!doctype html><p>Hi</p>',
      '<!-- generated by an agent -->\n<!doctype html><p>Hi</p>',
    ]) {
      expect(isFullHtmlDocument(content), JSON.stringify(content.slice(0, 40))).toBe(true);
    }
  });

  it('treats bare markup as a fragment that needs a shell', () => {
    for (const content of [
      '<h1>Weekly Ops</h1><p>Body</p>',
      '<div class="report"><table><tr><td>1</td></tr></table></div>',
      'Just a sentence.',
      '<!-- a comment --><section>Report</section>',
      '<htmlish-element>Not a document</htmlish-element>',
      '',
    ]) {
      expect(isFullHtmlDocument(content), JSON.stringify(content.slice(0, 40))).toBe(false);
    }
  });
});

describe('FrameDocument', () => {
  const fragment = '<h1>Weekly Ops</h1><p>The agent finished the work.</p>';

  it('gives a fragment the document shell a browser needs', () => {
    const html = FrameDocument({ content: fragment, title: 'Weekly Ops' });

    expect(html.toLowerCase().startsWith('<!doctype html>')).toBe(true);
    expect(html).toContain('<meta charset="utf-8">');
    expect(html).toContain('name="viewport"');
    expect(html).toContain('width=device-width');
    expect(html).toContain('<title>Weekly Ops</title>');
  });

  it('never modifies the agent content it wraps', () => {
    const hostile = `<p>a & b < c</p><button>Inline button</button><script>window.x=1</script>`;
    const html = FrameDocument({ content: hostile, title: 'Hostile' });

    expect(html).toContain(hostile);
    // The wrapper introduces no script of its own; the only one present is the agent's.
    expect(html.match(/<script/g) ?? []).toHaveLength(1);
  });

  it('introduces no script and no cross-origin request of its own', () => {
    const html = FrameDocument({ content: fragment, title: 'Weekly Ops' });

    expect(html).not.toContain('<script');
    // The sandbox origin cannot load the app stylesheet, so the shell must be self-contained.
    expect(html).not.toContain('<link');
    expect(html).not.toMatch(/https?:\/\//);
    expect(html).toContain('<style>');
  });

  it('passes a full document straight through, byte for byte', () => {
    const document = '<!doctype html><html lang="en"><body><h1>Mine</h1></body></html>';

    expect(FrameDocument({ content: document, title: 'Mine' })).toBe(document);
  });

  it('escapes the title without touching the body', () => {
    const html = FrameDocument({ content: fragment, title: '</title><script>alert(1)</script>' });

    expect(html).not.toContain('<script>alert(1)</script>');
    expect(html).toContain('&lt;/title&gt;');
  });

  it('defers to the agent: every baseline rule is a bare element selector', () => {
    const style = /<style>([\s\S]*?)<\/style>/.exec(
      FrameDocument({ content: fragment, title: 'Weekly Ops' })
    )?.[1];
    expect(style).toBeDefined();

    // A class or id in the shell would outrank the agent's own element styles. Everything here is
    // (0,0,1) or lower so any rule the agent writes wins.
    const selectors = Array.from((style as string).matchAll(/([^{}]+)\{/g), (match) =>
      (match[1] as string).trim()
    ).filter((selector) => selector && !selector.startsWith('@'));
    expect(selectors.length).toBeGreaterThan(5);
    for (const selector of selectors) {
      expect(selector, `"${selector.trim()}" is not a bare element selector`).not.toMatch(/[.#]/);
    }
    for (const property of ['font-family', 'line-height', 'max-width']) {
      expect(style, property).toContain(property);
    }
  });

  it('keeps its palette in step with the Fresh Air tokens', () => {
    const style = /<style>([\s\S]*?)<\/style>/.exec(
      FrameDocument({ content: fragment, title: 'Weekly Ops' })
    )?.[1] as string;

    const hexes = new Set((style.toLowerCase().match(/#[0-9a-f]{3,8}\b/g) ?? []).map(String));
    expect(hexes.size).toBeGreaterThan(0);
    for (const hex of hexes) {
      expect(appCss, `${hex} is not a Fresh Air token value`).toContain(hex);
    }
  });
});

describe('FrameTerminalDocument', () => {
  it('renders a branded, self-contained card instead of bare monospace text', () => {
    const html = FrameTerminalDocument({ status: 404, homeUrl: 'https://example.test' });

    expect(html.toLowerCase().startsWith('<!doctype html>')).toBe(true);
    expect(html).toContain('<meta charset="utf-8">');
    expect(html).toContain('name="viewport"');
    expect(html).toContain('<svg');
    expect(html).toContain('<style>');
    expect(html).not.toContain('<script');
    expect(html).not.toContain('<link');
  });

  it('says something true and different for each terminal cause', () => {
    const notFound = FrameTerminalDocument({ status: 404, homeUrl: 'https://example.test' });
    const gone = FrameTerminalDocument({ status: 410, homeUrl: 'https://example.test' });
    const locked = FrameTerminalDocument({ status: 401, homeUrl: 'https://example.test' });

    expect(notFound).not.toBe(gone);
    expect(gone).not.toBe(locked);
    expect(notFound).toContain('available here');
    expect(gone).toContain('no longer available');
    expect(locked).toContain('password-protected');
  });

  it('offers exactly one action, and points it somewhere real', () => {
    const html = FrameTerminalDocument({ status: 404, homeUrl: 'https://example.test/' });

    expect(html.match(/<a\b/g) ?? []).toHaveLength(1);
    expect(html).toContain('href="https://example.test/"');
  });

  it('escapes the destination it is given', () => {
    const html = FrameTerminalDocument({ status: 404, homeUrl: 'https://example.test/"><script>' });

    expect(html).not.toContain('"><script>');
  });
});
