import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import {
  FrameDocument,
  FrameTerminalDocument,
  isFullHtmlDocument,
} from '../../src/ui/pages/frame-document.js';

/**
 * Half the product's stated value is "every artifact is an HTML page", and that half shipped as a
 * raw fragment: `/a/:id/frame` returned `content.content` verbatim, with no doctype, no charset,
 * no viewport and no stylesheet, so agent HTML rendered in Times New Roman against the UA's 8px
 * body margin — at a public, directly-navigable URL.
 *
 * The shell wraps; it never rewrites. These tests hold that line, because the frame is also the
 * product's security boundary.
 */
const appCss = readFileSync('src/ui/assets/app.css', 'utf8').toLowerCase();

/** The sender as the fragment shell emits it, so both paths are asserted against one string. */
function heightSender(_html: string): string {
  const fragmentShell = FrameDocument({ content: '<p>x</p>', title: 't' });
  return /<script>([\s\S]*?)<\/script>/.exec(fragmentShell)?.[1] ?? '';
}

describe('full-document detection', () => {
  it('recognises content that already declares its own document', () => {
    for (const content of [
      '<!doctype html><h1>Hi</h1>',
      '<!DOCTYPE HTML><html><body>Hi</body></html>',
      '  \n<!doctype html>\n<html lang="en"></html>',
      '<html><head></head><body>Hi</body></html>',
      '﻿<!doctype html><p>Hi</p>',
      '<!-- generated by an agent -->\n<!doctype html><p>Hi</p>',
    ]) {
      expect(isFullHtmlDocument(content), JSON.stringify(content.slice(0, 40))).toBe(true);
    }
  });

  it('treats bare markup as a fragment that needs a shell', () => {
    for (const content of [
      '<h1>Weekly Ops</h1><p>Body</p>',
      '<div class="report"><table><tr><td>1</td></tr></table></div>',
      'Just a sentence.',
      '<!-- a comment --><section>Report</section>',
      '<htmlish-element>Not a document</htmlish-element>',
      '',
    ]) {
      expect(isFullHtmlDocument(content), JSON.stringify(content.slice(0, 40))).toBe(false);
    }
  });
});

describe('FrameDocument', () => {
  const fragment = '<h1>Weekly Ops</h1><p>The agent finished the work.</p>';

  it('gives a fragment the document shell a browser needs', () => {
    const html = FrameDocument({ content: fragment, title: 'Weekly Ops' });

    expect(html.toLowerCase().startsWith('<!doctype html>')).toBe(true);
    expect(html).toContain('<meta charset="utf-8">');
    expect(html).toContain('name="viewport"');
    expect(html).toContain('width=device-width');
    expect(html).toContain('<title>Weekly Ops</title>');
  });

  it('never modifies the agent content it wraps', () => {
    const hostile = `<p>a & b < c</p><button>Inline button</button><script>window.x=1</script>`;
    const html = FrameDocument({ content: hostile, title: 'Hostile' });

    // The agent's bytes survive exactly, including its own script — that is what this test is for,
    // and it is unaffected by A-25.
    expect(html).toContain(hostile);
    expect(html).toContain('<script>window.x=1</script>');
    // Two scripts now: the agent's, and the height sender this shell appends after the content.
    // The count is asserted so a third can never arrive unnoticed.
    expect(html.match(/<script/g) ?? []).toHaveLength(2);
    expect(
      html.indexOf('window.x=1'),
      'the sender was injected before the agent content'
    ).toBeLessThan(html.indexOf('aa:frame-height'));
  });

  it('sends its measured height to the embedder, and only that', () => {
    const html = FrameDocument({ content: '<h1>Fragment</h1>', title: 'Fragment' });

    // A-25: the viewer has always listened for `aa:frame-height`; nothing ever sent it, so every
    // HTML artifact clamped at the CSS default of 432px regardless of its content.
    expect(html).toContain("type:'aa:frame-height'");
    expect(html).toContain('scrollHeight');
    // Inert by construction: it posts one fixed-shape message and does nothing else. It never reads
    // from the parent, touches no cookie or storage, makes no request, and mutates no DOM.
    expect(html).toContain('window.parent===window');
    for (const forbidden of [
      'document.cookie',
      'localStorage',
      'fetch(',
      'XMLHttpRequest',
      'innerHTML',
    ]) {
      expect(html, `height sender reaches for ${forbidden}`).not.toContain(forbidden);
    }
  });

  it('gives a document the agent wrote whole the height sender, and nothing else', () => {
    // THE ASSERTION THIS REPLACES IS THE DEFECT, WRITTEN DOWN.
    //
    // It required a full document to come back byte-identical, "keeping the 432px clamp as an
    // accepted limit" — and every HTML artifact this product publishes from a template is a full
    // document, because the templates are. Measured on the shipped product: the recap rendered in a
    // 746px frame holding 5271px on a phone, so a reader saw 14% of it inside a nested scrollbar on
    // a page that did not itself scroll.
    //
    // The height is not a decision the document makes. It is a measurement only the document can
    // take and only the embedder can act on, across an origin boundary neither can reach through.
    const full =
      '<!doctype html><html><head><title>Whole</title></head><body><p>Mine</p></body></html>';
    const html = FrameDocument({ content: full, title: 'ignored' });

    expect(html.startsWith(full), 'the agent bytes must still lead, unaltered').toBe(true);
    expect(html.slice(full.length)).toBe(`<script>${heightSender(html)}</script>`);
    expect(html).toContain("type:'aa:frame-height'");
    // Exactly one script is added, and it is the audited one. A second would be a new capability.
    expect(html.slice(full.length).match(/<script/g) ?? []).toHaveLength(1);
  });

  it('adds nothing to a whole document but the sender — no shell, no style, no request', () => {
    const full = '<!doctype html><html><head><title>Whole</title></head><body>x</body></html>';
    const appended = FrameDocument({ content: full, title: 'ignored' }).slice(full.length);

    for (const forbidden of ['<style', '<link', '<meta', 'http://', 'https://']) {
      expect(appended, `the append reaches for ${forbidden}`).not.toContain(forbidden);
    }
  });

  it('introduces no cross-origin request of its own', () => {
    const html = FrameDocument({ content: fragment, title: 'Weekly Ops' });

    // The height sender is the one script this shell adds — see the test above. The invariant is
    // now "adds only the audited height sender", not "adds no script": the sandbox already runs the
    // agent's own scripts under `allow-scripts`, so this adds no capability that was not present.
    expect(html.match(/<script/g) ?? []).toHaveLength(1);
    // The sandbox origin cannot load the app stylesheet, so the shell must be self-contained.
    expect(html).not.toContain('<link');
    expect(html).not.toMatch(/https?:\/\//);
    expect(html).toContain('<style>');
  });

  it('leaves the agent bytes of a full document exactly as written', () => {
    // The half of the old assertion that was always right: this module may append, and may never
    // reach inside. Nothing is parsed, nothing is rewritten, and the document the agent published
    // is a literal prefix of what the frame serves.
    const document = '<!doctype html><html lang="en"><body><h1>Mine</h1></body></html>';
    const html = FrameDocument({ content: document, title: 'Mine' });

    expect(html.startsWith(document)).toBe(true);
    expect(html.indexOf(document)).toBe(0);
    expect(html.replace(/<script>[\s\S]*<\/script>$/, '')).toBe(document);
  });

  it('escapes the title without touching the body', () => {
    const html = FrameDocument({ content: fragment, title: '</title><script>alert(1)</script>' });

    expect(html).not.toContain('<script>alert(1)</script>');
    expect(html).toContain('&lt;/title&gt;');
  });

  it('defers to the agent: every baseline rule is a bare element selector', () => {
    const style = /<style>([\s\S]*?)<\/style>/.exec(
      FrameDocument({ content: fragment, title: 'Weekly Ops' })
    )?.[1];
    expect(style).toBeDefined();

    // A class or id in the shell would outrank the agent's own element styles. Everything here is
    // (0,0,1) or lower so any rule the agent writes wins.
    const selectors = Array.from((style as string).matchAll(/([^{}]+)\{/g), (match) =>
      (match[1] as string).trim()
    ).filter((selector) => selector && !selector.startsWith('@'));
    expect(selectors.length).toBeGreaterThan(5);
    for (const selector of selectors) {
      expect(selector, `"${selector.trim()}" is not a bare element selector`).not.toMatch(/[.#]/);
    }
    for (const property of ['font-family', 'line-height', 'max-width']) {
      expect(style, property).toContain(property);
    }
  });

  it('keeps its palette in step with the Fresh Air tokens', () => {
    const style = /<style>([\s\S]*?)<\/style>/.exec(
      FrameDocument({ content: fragment, title: 'Weekly Ops' })
    )?.[1] as string;

    const hexes = new Set((style.toLowerCase().match(/#[0-9a-f]{3,8}\b/g) ?? []).map(String));
    expect(hexes.size).toBeGreaterThan(0);
    for (const hex of hexes) {
      expect(appCss, `${hex} is not a Fresh Air token value`).toContain(hex);
    }
  });
});

describe('FrameTerminalDocument', () => {
  it('renders a branded, self-contained card instead of bare monospace text', () => {
    const html = FrameTerminalDocument({ status: 404, homeUrl: 'https://example.test' });

    expect(html.toLowerCase().startsWith('<!doctype html>')).toBe(true);
    expect(html).toContain('<meta charset="utf-8">');
    expect(html).toContain('name="viewport"');
    expect(html).toContain('<svg');
    expect(html).toContain('<style>');
    expect(html).not.toContain('<script');
    expect(html).not.toContain('<link');
  });

  it('says something true and different for each terminal cause', () => {
    const notFound = FrameTerminalDocument({ status: 404, homeUrl: 'https://example.test' });
    const gone = FrameTerminalDocument({ status: 410, homeUrl: 'https://example.test' });
    const locked = FrameTerminalDocument({ status: 401, homeUrl: 'https://example.test' });

    expect(notFound).not.toBe(gone);
    expect(gone).not.toBe(locked);
    expect(notFound).toContain('available here');
    expect(gone).toContain('no longer available');
    expect(locked).toContain('password-protected');
  });

  it('offers exactly one action, and points it somewhere real', () => {
    const html = FrameTerminalDocument({ status: 404, homeUrl: 'https://example.test/' });

    expect(html.match(/<a\b/g) ?? []).toHaveLength(1);
    expect(html).toContain('href="https://example.test/"');
  });

  it('escapes the destination it is given', () => {
    const html = FrameTerminalDocument({ status: 404, homeUrl: 'https://example.test/"><script>' });

    expect(html).not.toContain('"><script>');
  });
});
