import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { isHashedMediaPath } from '../../src/ui/assets.js';
import { LAUNCH_VIDEO } from '../../src/ui/marketing-video-media.js';

// Approved encodes/posters are adopted, not regenerated by the application build. These full
// hashes bind the four delivered assets; updating the film requires an explicit media review.
const approved = {
  desktop: 'eccb5261ce8a945ef779ecb2575241ddd9f7d615cddce7cb99a2c6451df14cd1',
  phone: 'debfd582ad844195d4af3a7cb8321f563edf16c23afc457588785066f0f75075',
  posterPhone: '83c10656873f7de8c2f3b52609f8c23d51c7c63557a0b4b144f30db297d2be88',
  posterDesktop: '13ccf9f3467fcdd8177563613b8771e854ccc70852208bf5ff0e1691979979bb',
};

describe('the shipped homepage film', () => {
  it.each(Object.entries(LAUNCH_VIDEO))(
    'ships %s under its own actual content hash',
    (key, url) => {
      const bytes = readFileSync(`public${url}`);
      const digest = createHash('sha256').update(bytes).digest('hex');
      expect(isHashedMediaPath(url)).toBe(true);
      expect(url).toContain(`.${digest.slice(0, 16)}.`);
      if (key in approved) expect(digest).toBe(approved[key as keyof typeof approved]);
    }
  );

  it.each(['phone', 'desktop'] as const)(
    'keeps %s faststart, with the metadata ahead of movie data',
    (key) => {
      const bytes = readFileSync(`public${LAUNCH_VIDEO[key]}`);
      const boxes: string[] = [];
      let offset = 0;
      while (offset < bytes.length) {
        const size = bytes.readUInt32BE(offset);
        expect(size).toBeGreaterThanOrEqual(8);
        boxes.push(bytes.toString('ascii', offset + 4, offset + 8));
        offset += size;
      }
      expect(offset).toBe(bytes.length);
      expect(boxes).toContain('moov');
      expect(boxes.indexOf('moov')).toBeLessThan(boxes.indexOf('mdat'));
    }
  );

  it('keeps the optional timed visual alternative factual and available without replacing the film', () => {
    const text = readFileSync(`public${LAUNCH_VIDEO.captions}`, 'utf8');
    expect(text.startsWith('WEBVTT\n')).toBe(true);
    expect(text).toContain('Descriptive visual transcript');
    expect(text.match(/ --> /g)).toHaveLength(5);
    expect(text).toContain('00:00:00.000 --> 00:00:08.000');
    expect(text).toContain('00:00:35.000 --> 00:00:46.000');
    expect(text).toContain('Earlier versions remain available');
    expect(text).toContain('“Publish your agent’s work.”');
    expect(text).not.toMatch(/\[music\]|\[.*sound.*\]/i);
  });
});
